sudo: required
services:
 - docker

before_install:
 - docker build -t neosystemcouk/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run CI=true neosystemcouk/react-test npm test

after_succses:
 - docker build -t neosystemcouk/multi-client ./client
 - docker build -t neosystemcouk/multi-nginx ./nginx
 - docker build -t neosystemcouk/multi-server ./server
 - docker build -t neosystemcouk/multi-worker ./worker
 #Login to the docker CLI
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 #push to dockerhub
 - docker push neosystemcouk/multi-client
 - docker push neosystemcouk/multi-nginx
 - docker push neosystemcouk/multi-server
 - docker push neosystemcouk/multi-worker

